### ISSUE TITLE
Tâche 5.1 - Mes tâches (GN)

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#396]
- [ ] Page layout
- [ ] Search results: Chaque bloc représente une tâche. Il contient des informations permettant d'identifier la fiche (vignette et titre), la description de la tâche demandée sous forme d'injonction, l'échéance de réalisation de l'action composée de la date due et du nombre de jours restants pour effectuer la tâche. Si l'échéance est dépassée, la mention "En retard" est affichée. 
- [ ] Sort by dueDate
- [x] Click trigger the task
- [x] Button to create a new task
- [x] Popup to create a task

```
* Destinataire (obligatoire) - Email de l’utilisateur (avec auto-complétion). 
Si l’utilisateur n’est pas référencé au niveau des utilisateurs Metawal,  un compte est automatiquement créé dans metawal et les informations de connexion lui sont envoyées. Un notification est envoyée à l’administration du catalogue pour informer de la création d’un nouveau compte. Voir la config ldap user auth or admin account

* Pour les tâches de validation et de publication, le destinataire est auto-complété selon les informations enregistrées dans le système.
 * Pour une modification, l’utilisateur doit être au moins un éditeur 
 * Pour une validation, l’utilisateur doit être au moins un éditeur
 * Pour la publication, l’utilisateur doit être un relecteur ou un administrateur du catalogue
* Fiche (obligatoire) - identifiant ou titre de la métadonnée.
* Section (uniquement disponible pour les tâches de complétude et de validation de section - obligatoire) 
* Échéance (optionnel) - date d’échéance de la tâche.

```

Au niveau du système de tasking, trois rôles se distinguent: 
* Le coordinateur d'édition - il crée la fiche.
* Le validateur - il est le gestionnaire de la ressource, défini lors de l'édition de la fiche dans la section des contacts (ou bien un validateur désigné).
* Le publicateur - il est défini pour toutes les fiches par l'administrateur de Metawal, dans l'interface d'administration (sauf si délégation).

- [x] Status is redesigned as a task
* Created
* SectionChangeRequested (possible d'avoir n tâches de ce type en //)
* SectionValidationRequested
* ValidationRequested
* PublicationRequested
* Approved

- [ ] Delegate to someone
- [x] Task notification & rule check system in DefaultStatusAction
 - [ ] une fiche ne peut passer à l'étape de validation que si le coordinateur de l'édition a renseigné le gestionnaire de la ressource (c qui ? dans le XML ou dans les users du catalogue ?). 

## DB changes

**Task or using status table**

- [x] requesterId [key] - currently named userId
- [x] ownerId (new)
- [x] metadataId  [key]
- [x] creationDate  [key] - currently named changeDate
- [x] dueDate (new)
- [x] message
- [x] status
- [ ] delegatedAs (new) - n délégations ? - maybe we could simply change the owner ? Do we need to track history of delegations ?
- [x] targetSection (new)
- [ ] closed (new) - not sure this is needed - we can use close date
- [x] closeDate (new)

**TaskRaise**
* userId
* taskId
* raiseDate

## API

* GET /api/tasks: Rechercher des tâches (avec tri, filtre, pagination)
* GET /api/users/{userid}/tasks: Récupérer les tâches d'un utilisateur
* GET /api/records/{uuid}/tasks: Récupérer les tâches d'une fiche
* PUT /api/records/{uuid}/tasks: Créer une nouvelle tâche
* POST /api/records/{uuid}/tasks/{taskId}: Mettre à jour une tâche existante
* PUT /api/records/{uuid}/tasks/{taskId}/transfertTo/{userId}: Déléguer une tâche
* DELETE /api/records/{uuid}/tasks/{taskId}: Supprimer une tâche existante (et notifie le propriétaire)

**Comment by davinciagf** [comment]
Related to https://github.com/geonetwork/core-geonetwork/pull/3209

**Comment by fxprunayre** [comment]
A traiter dans un cas simple cf. #3209
