### ISSUE TITLE
Test complet de la v 3.4.0

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#418]
Test complet de la version 3.4.0
Ticket en cours d'édition...

# Consultation
## Facettes
- [x] #417 - Valeur bizarre dans la facette "type de de ressource"
- [x] #419 - Traduction

Il y a des problèmes spécifiques aux facettes "Géoportail". On peut les laisser comme ça mais c'est à tenir à l'oeil dans une version ultérieure
- [x] #420 - Facette géoportail "Diffusion via"
- [x] #421 - Facettes et ISO 19115-3 
- [x] #422 - Facettes doublon

## Recherche full text
- RAS

## Recherche avancée
- [x] #428 - Recherche prédictive sur les contacts
- [x] #429 - Différence recherche avancée et facettes pour mots-clés provenant d'un thésaurus
- [x] #430 - Mots-clés sortant du cadre
- [x] #431 - Problèmes avec les recherches sur les dates
- [x] #364 - Suppression du critère "catégorie"
- Combinaison recherche avancée et facettes : OK

## Résultats de la recherche
- [ ] #367 - comme ça doit être réglé pour la version intégrée Géoportail, je l'ai mis en v 3.4.1
- [x] #425 - pagination NaN
- [x] #414 - Tri par date de mise à jour
- Affiner une recherche via restriction à la sélection : OK
- Partage des recherches via lien : OK
- #432 - Différence dans le décompte du nombre de résultats

## Fiche individuelle
- [ ] #339 - Configurer les vues disponibles : c'est le boxon là-dedans !! 
- [x] #373 - Vue géoportail
- [ ] #403 - Mise en page
- [ ] #426 - Traductions sur vue GP --> pour v 3.4.1

# Connexion / Déconnexion / préférences utilisateurs
Les améliorations seront traitées dans une future release sur projet DIG-2017-M11/A
- [ ] #299 - Messages d'erreur et récupération des identifiants et mdp

# Edition
## Edition d'une fiche
- [x] #356 - Problèmes formulaire d'édition vue GP
- [ ] #357 - Problèmes formulaire d'édition vue GP
- [ ] #437 - Edition - Formulaire d'édition ne s'affiche pas

## Ressources associées
- [ ] #325 - association donnée-service : liste des suggestions qui s'affiche aléatoirement quand on tape
- [ ] #328 - Affichage des services liés à une donnée
- [ ] #381 - Référencement des ressources associées
- [ ] #405 - Ajout WMS : layer group

## Edition multiple
- [x] #409 - Edition multiple et facettes

# Publication
- [x] #424 - Difficulté de publier des fiches

# Import/export
## Moissonnage
- [ ] #336 Problème avec la transformation 19139-->19115-3

## Import/export MEF
- [x] #423 Import et imagettes 19139 vs 19115-3 - pour info
- [ ] #346 Problème à l'export d'un grand nombre de fiches

## Divers
- [x] #412 - Import, et édition de mots-clés provenant d'un thésaurus
- [ ] #436 - Déclaration et conformité des schémas - question

# INSPIRE
- [ ] #316 - Problèmes de conformité
- [ ] #434  - INSPIRE - Erreur de validation
- [x] #435   - Validation INSPIRE des fiches
- [ ] #447 - Compléter automatiquement la date et l'explication

# GeoCatalogue
- [ ] #433 - GeoCatalogue - Eléments non récupérés

# Documentation
- [ ] #416 - Paramètres pour l'interface

# Divers
- [x] #406 - Coquilles
- [x] #410 - Lenteurs bloquantes de l'application

**Comment by fxprunayre** [comment]
Pour la suite, utiliser une milestone ou un projet pour le suivi.
